name = "ProcessTracer"
uuid = "4116e063-1027-4a0b-8ebe-6c795146b3dd"
authors = ["Julian P Samaroo <jpsamaroo@jpsamaroo.me>"]
version = "0.1.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
CEnum = "0.4"
julia = "1"
